// ==========================================================================
// PHOTOGRAPHY PORTFOLIO DATA (LOADED FROM data.js)
// ==========================================================================
// ALBUMS_DATA is now loaded dynamically from data.js, which is automatically
// generated by running the Python automation script: python3 update_gallery.py


// ==========================================================================
// STATE MANAGEMENT
// ==========================================================================
let currentAlbumPhotos = [];
let currentPhotoIndex = 0;

// ==========================================================================
// ROUTER & NAVIGATION
// ==========================================================================
function router() {
    const hash = window.location.hash || '#/';
    
    // Hide all views
    document.querySelectorAll('.view').forEach(view => {
        view.classList.remove('active');
    });
    
    // Update navigation active state
    document.querySelectorAll('.nav-link').forEach(link => {
        link.classList.remove('active');
    });

    if (hash === '#/' || hash === '') {
        // Render Home
        document.getElementById('home-view').classList.add('active');
        document.getElementById('nav-home').classList.add('active');
        renderAlbums();
        window.scrollTo({ top: 0, behavior: 'smooth' });
    } else if (hash === '#/about') {
        // Render About
        document.getElementById('about-view').classList.add('active');
        document.getElementById('nav-about').classList.add('active');
        window.scrollTo({ top: 0, behavior: 'smooth' });
    } else if (hash.startsWith('#/album/')) {
        // Render Album Details
        const albumId = hash.replace('#/album/', '');
        const album = ALBUMS_DATA.find(a => a.id === albumId);
        
        if (album) {
            renderAlbumDetail(album);
            document.getElementById('album-view').classList.add('active');
            window.scrollTo({ top: 0, behavior: 'smooth' });
        } else {
            // Album not found, redirect to home
            window.location.hash = '#/';
        }
    } else {
        // Unknown route, fallback to home
        window.location.hash = '#/';
    }
}

// Listen to navigation events
window.addEventListener('hashchange', router);
window.addEventListener('DOMContentLoaded', router);

// ==========================================================================
// DOM RENDERING
// ==========================================================================

// Render Album cards on the homepage
function renderAlbums() {
    const albumsGrid = document.getElementById('albums-grid');
    albumsGrid.innerHTML = '';
    
    ALBUMS_DATA.forEach(album => {
        const card = document.createElement('article');
        card.className = 'album-card';
        card.innerHTML = `
            <div class="album-img-wrapper">
                <img src="${album.cover}" alt="${album.title}" loading="lazy">
            </div>
            <div class="album-info">
                <h3 class="album-card-title">${album.title}</h3>
                <p class="album-card-desc">${album.description}</p>
                <div class="album-card-meta">
                    <span>${album.meta}</span>
                    <span class="album-card-link">
                        Apri Album 
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                            <polyline points="12 5 19 12 12 19"></polyline>
                        </svg>
                    </span>
                </div>
            </div>
        `;
        
        // Navigation on click
        card.addEventListener('click', () => {
            window.location.hash = `#/album/${album.id}`;
        });
        
        albumsGrid.appendChild(card);
    });
}

// Render Photos in the album detail view
function renderAlbumDetail(album) {
    document.getElementById('album-title').textContent = album.title;
    document.getElementById('album-description').textContent = album.description;
    
    const photosGrid = document.getElementById('photos-grid');
    photosGrid.innerHTML = '';
    
    currentAlbumPhotos = album.photos;
    
    album.photos.forEach((photo, index) => {
        const card = document.createElement('div');
        card.className = `photo-card ${photo.aspectRatio === 'portrait' ? 'portrait-ratio' : ''}`;
        card.innerHTML = `
            <div class="photo-img-wrapper">
                <img src="${photo.url}" alt="${photo.title}" loading="lazy">
            </div>
            <div class="photo-caption">
                <h3 class="photo-title">${photo.title}</h3>
                <p class="photo-desc">${photo.caption}</p>
                <span class="photo-meta">${photo.meta}</span>
            </div>
        `;
        
        // Open Lightbox on click
        card.addEventListener('click', () => {
            openLightbox(index);
        });
        
        photosGrid.appendChild(card);
    });
}

// ==========================================================================
// LIGHTBOX CONTROLLER
// ==========================================================================
const lightbox = document.getElementById('lightbox');
const lightboxImg = document.getElementById('lightbox-image');
const lightboxCap = document.getElementById('lightbox-caption');
const closeBtn = document.getElementById('lightbox-close');
const prevBtn = document.getElementById('lightbox-prev');
const nextBtn = document.getElementById('lightbox-next');

function openLightbox(index) {
    currentPhotoIndex = index;
    updateLightboxContent();
    lightbox.classList.add('active');
    lightbox.setAttribute('aria-hidden', 'false');
    document.body.style.overflow = 'hidden'; // Stop page scrolling
    
    // Attach keyboard event listeners
    window.addEventListener('keydown', handleKeyDown);
}

function closeLightbox() {
    lightbox.classList.remove('active');
    lightbox.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = ''; // Restore scrolling
    
    // Clean up keyboard event listeners
    window.removeEventListener('keydown', handleKeyDown);
}

function updateLightboxContent() {
    if (!currentAlbumPhotos.length) return;
    const photo = currentAlbumPhotos[currentPhotoIndex];
    
    // Visual transition
    lightboxImg.style.opacity = '0';
    lightboxCap.style.opacity = '0';
    
    setTimeout(() => {
        lightboxImg.src = photo.url;
        lightboxImg.alt = photo.title;
        
        lightboxCap.innerHTML = `
            <strong>${photo.title}</strong>
            <div style="font-size: 0.9rem; color: var(--text-secondary); margin-top: 6px; font-family: var(--font-sans); font-weight: 300;">
                ${photo.caption}
            </div>
            <div style="font-size: 0.75rem; color: var(--text-muted); margin-top: 8px; font-family: monospace;">
                ${photo.meta}
            </div>
        `;
        
        lightboxImg.style.opacity = '1';
        lightboxCap.style.opacity = '1';
    }, 150);
}

function nextPhoto() {
    currentPhotoIndex = (currentPhotoIndex + 1) % currentAlbumPhotos.length;
    updateLightboxContent();
}

function prevPhoto() {
    currentPhotoIndex = (currentPhotoIndex - 1 + currentAlbumPhotos.length) % currentAlbumPhotos.length;
    updateLightboxContent();
}

// Keyboard controls
function handleKeyDown(e) {
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowRight') nextPhoto();
    if (e.key === 'ArrowLeft') prevPhoto();
}

// Lightbox click events
closeBtn.addEventListener('click', closeLightbox);
prevBtn.addEventListener('click', (e) => {
    e.stopPropagation(); // Avoid closing lightbox
    prevBtn.blur();
    prevPhoto();
});
nextBtn.addEventListener('click', (e) => {
    e.stopPropagation(); // Avoid closing lightbox
    nextBtn.blur();
    nextPhoto();
});

// Click outside image to close lightbox
lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox || e.target.classList.contains('lightbox-content')) {
        closeLightbox();
    }
});
